language: generic
sudo: false
branches:
  except:
  - ___TGS3TempBranch
env:
    global:
    - BYOND_MAJOR="512"
    - BYOND_MINOR="1418"
    - NODE_VERSION="4"
    - BUILD_TOOLS=false
    - BUILD_TESTING=false
    - DM_MAPFILE="loadallmaps"
    matrix:
    - BUILD_TESTING=true

cache:
  directories:
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}


addons:
  apt:
    packages:
      - libc6-i386
      - libgcc1:i386
      - libstdc++6:i386

before_script:
  - tools/travis/before_build_byond.sh

script:
  - tools/travis/check_filedirs.sh tgstation.dme
  - tools/travis/build_byond.sh

